enableGlobalCache: false

packageExtensions:
  '@apollo/client@*':
    dependencies:
      '@types/zen-observable': '*'
    peerDependencies:
      react-dom: '*'
  '@apollo/link-error@*':
    peerDependencies:
      graphql: '*'
      react: '*'
      react-dom: '*'
  '@apollo/react-ssr@*':
    peerDependencies:
      graphql: '*'
      react: '*'
      react-dom: '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls-ui-parts/link@*':
    dependencies:
      '@emotion/css': '*'
  '@atls/next-app-with-apollo@*':
    dependencies:
      '@types/zen-observable': '*'
    peerDependencies:
      next: '*'
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
  '@react-three/drei@*':
    dependencies:
      three-stdlib: 'patch:three-stdlib@npm%3A2.28.9#~/.yarn/patches/three-stdlib-npm-2.28.9-598c595c00.patch'
  framer-motion@*:
    dependencies:
      csstype: '*'
  react-locomotive-scroll@*:
    dependencies:
      tslib: '*'
  swiper@*:
    dependencies:
      react: '*'

yarnPath: .yarn/releases/yarn-file.cjs
