packageExtensions:
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
  '@apollo/client@*':
    dependencies:
      '@types/zen-observable': '*'
    peerDependencies:
      react-dom: '*'
  '@apollo/link-error@*':
    peerDependencies:
      graphql: '*'
      react: '*'
      react-dom: '*'
  '@apollo/react-ssr@*':
    peerDependencies:
      graphql: '*'
      react: '*'
      react-dom: '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls-ui-parts/link@*':
    dependencies:
      '@emotion/css': '*'
  '@atls/next-app-with-apollo@*':
    dependencies:
      '@types/zen-observable': '*'
    peerDependencies:
      next: '*'
  framer-motion@*:
    dependencies:
      csstype: '*'
  swiper@*:
    dependencies:
      react: '*'
  react-locomotive-scroll@*:
    dependencies:
      tslib: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220605.hash-c4f9c8f.cjs
