version: '3.8'

services:
  yarn:
    image: node:16.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  wordpress:
    image: atlantislab/misik-wp
    ports:
      - 8080:80
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes/
      - wordpress:/var/www/html
      - ./.ignore/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - ./.ignore/wp-content/uploads/:/var/www/html/wp-content/uploads/
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  landing:
    image: node:16.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @landing/app dev
    environment:
      - WP_ENDPOINT=https://wp.misik.pro/graphql
    ports:
      - 3000:3000
    env_file:
      - ./.env

volumes:
  wordpress:
  db:
