version: '3.8'

services:
  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - ./.ignore/wp-content/plugins/:/var/www/html/wp-content/plugins/
      - ./.ignore/wp-content/themes/:/var/www/html/wp-content/themes/
      - ./.ignore/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  landing:
    image: node:16-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @landing/app dev
    environment:
      - WP_ENDPOINT=http://localhost:8080
    depends_on:
      - wordpress
    ports:
      - 3000:3000

volumes:
  wordpress:
  db:
